package com.zybaiyou.wycfuser.mapper;

import com.zybaiyou.wycfuser.pojo.wy_tb_test;
import com.zybaiyou.wycfuser.pojo.wy_tb_testExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface wy_tb_testMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_tb_test
     *
     * @mbggenerated
     */
    int countByExample(wy_tb_testExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_tb_test
     *
     * @mbggenerated
     */
    int deleteByExample(wy_tb_testExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_tb_test
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_tb_test
     *
     * @mbggenerated
     */
    int insert(wy_tb_test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_tb_test
     *
     * @mbggenerated
     */
    int insertSelective(wy_tb_test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_tb_test
     *
     * @mbggenerated
     */
    List<wy_tb_test> selectByExample(wy_tb_testExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_tb_test
     *
     * @mbggenerated
     */
    wy_tb_test selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_tb_test
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") wy_tb_test record, @Param("example") wy_tb_testExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_tb_test
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") wy_tb_test record, @Param("example") wy_tb_testExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_tb_test
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(wy_tb_test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wy_tb_test
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(wy_tb_test record);
}